### ISSUE TITLE
用你的模版创建的项目，无法迁移

### ISSUE THREAD

**Issue by BraveJJJ** [colinin/abp-next-admin#1011]
PM> add-migration Added_something -verbose
Using project 'src\PackageName.CompanyName.test.EntityFrameworkCore'.
Using startup project 'host\PackageName.CompanyName.test.HttpApi.Host'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host\bin\Debug\net8.0\PackageName.CompanyName.test.HttpApi.Host.deps.json --additionalprobingpath C:\Users\Administrator\.nuget\packages --additionalprobingpath "g:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --runtimeconfig D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host\bin\Debug\net8.0\PackageName.CompanyName.test.HttpApi.Host.runtimeconfig.json C:\Users\Administrator\.nuget\packages\microsoft.entityframeworkcore.tools\8.0.8\tools\netcoreapp2.0\any\ef.dll migrations add Added_something --json --verbose --no-color --prefix-output --assembly D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host\bin\Debug\net8.0\PackageName.CompanyName.test.EntityFrameworkCore.dll --project D:\TestCode\test\src\PackageName.CompanyName.test.EntityFrameworkCore\PackageName.CompanyName.test.EntityFrameworkCore.csproj --startup-assembly D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host\bin\Debug\net8.0\PackageName.CompanyName.test.HttpApi.Host.dll --startup-project D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host\PackageName.CompanyName.test.HttpApi.Host.csproj --project-dir D:\TestCode\test\src\PackageName.CompanyName.test.EntityFrameworkCore\ --language C# --configuration Debug --working-dir D:\TestCode\test --root-namespace ""
Using assembly 'PackageName.CompanyName.test.EntityFrameworkCore'.
Using startup assembly 'PackageName.CompanyName.test.HttpApi.Host'.
Using application base 'D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host\bin\Debug\net8.0'.
Using working directory 'D:\TestCode\test\host\PackageName.CompanyName.test.HttpApi.Host'.
Using root namespace ''.
Using project directory 'D:\TestCode\test\src\PackageName.CompanyName.test.EntityFrameworkCore\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider in assembly 'PackageName.CompanyName.test.HttpApi.Host'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Finding DbContext classes in the project...
Found DbContext 'testDbContext'.
Using DbContext factory 'testDbContextFactory'.
Using context 'testDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create a 'DbContext' of type ''. The exception 'Value cannot be null. (Parameter 'provider')' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at LINGYUN.Abp.DataProtection.EntityFrameworkCore.AbpDataProtectionDbContext`1.OnConfiguring(DbContextOptionsBuilder optionsBuilder)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService(IInfrastructure`1 accessor, Type serviceType)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
**Unable to create a 'DbContext' of type ''. The exception 'Value cannot be null. (Parameter 'provider')' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728**

**Comment by BraveJJJ** [comment]
![image](https://github.com/user-attachments/assets/94265df0-ecea-40cf-a044-db46bfb8e7a0)

**Comment by colinin** [comment]
由于迁移的DbContext不是由容器创建的, 所以这里有个小问题, 8.3.0 版本修复

https://github.com/colinin/abp-next-admin/blob/8b462018e8873f2dbcdbb11cd0450d9ec9d14a70/aspnet-core/templates/content/src/PackageName.CompanyName.ProjectName.EntityFrameworkCore/PackageName/CompanyName/ProjectName/EntityFrameworkCore/ProjectNameDbContextFactory.cs#L9-L37

**Comment by BraveJJJ** [comment]
是啊，db上下文继承IDesignTimeDbContextFactory这个接口，迁移时不会走ioc那套，直接从这个类启动，所以很多拿不到值，IDesignTimeDbContextFactory的目的是更灵活控制迁移吗？有什么区别

**Comment by BraveJJJ** [comment]
另外迁移时，好像都不需要涉及到数据（权限）保护吧

**Comment by colinin** [comment]
> 另外迁移时，好像都不需要涉及到数据（权限）保护吧

只是新项目继承自这个上下文而已，如果你的实体没有启用数据保护，不会受任何影响
