### ISSUE TITLE
下载最新版本运行数据迁移报错

### ISSUE THREAD

**Issue by jim-liao** [colinin/abp-next-admin#504]
HttpApi.Host>dotnet ef database update
Build started...
Build succeeded.
2022-02-25 16:05:49 [FTL] [] [9420] [4] - Host terminated unexpectedly!
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostExce
ption: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+Hosti
ngListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(Ke
yValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at LY.MicroService.BackendAdmin.Program.Main(String[] args) in E:\learn-proje
ct\abpnextadmin\aspnet-core\services\LY.MicroService.BackendAdmin.HttpApi.Host\P
rogram.cs:line 49
Host terminated unexpectedly!

**Comment by colinin** [comment]
迁移出错请检查项目appsettings.json或appsettings.Development.json中，ConnectionStrings配置

**Comment by lszai90** [comment]
这个不影响迁移的、在项目中的IHostBulder.Build()周围添加类似于try/catch，尝试添加迁移可能会出现该问题。 是不是大佬@Colinin

**Comment by colinin** [comment]
不影响迁移成功，这个应该是ef 6.0.2 tools的一个问题，我抽空再看看吧

**Comment by luchaoshuai** [comment]
ConnectionStrings上面写了sql server的连接字符串，如何切换到sql server？

**Comment by colinin** [comment]
升级 dotnet-ef 工具库可解决
