### ISSUE TITLE
内部网关启动错误

### ISSUE THREAD

**Issue by sonce** [colinin/abp-next-admin#644]
你好，启动内部网关出现下面这个错误。
没有头绪，不知道哪里问题。
希望指导下。

``` shell
Volo.Abp.AbpInitializationException: An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module LINGYUN.MicroService.Internal.ApiGateway.InternalApiGatewayModule, LINGYUN.MicroService.Internal.ApiGateway, Version=5.3.2.0, Culture=neutral, PublicKeyToken=null: One or more errors occurred. (Unable to start Ocelot, errors are: Routes for aggregateRoute /api/setting-management/settings/by-global either do not exist or do not have correct ServiceName property,Routes for aggregateRoute /api/setting-management/settings/by-current-tenant either do not exist or do not have correct ServiceName property,Routes for aggregateRoute /api/setting-management/settings/by-current-user either do not exist or do not have correct ServiceName property). See the inner exception for details.
 ---> System.AggregateException: One or more errors occurred. (Unable to start Ocelot, errors are: Routes for aggregateRoute /api/setting-management/settings/by-global either do not exist or do not have correct ServiceName property,Routes for aggregateRoute /api/setting-management/settings/by-current-tenant either do not exist or do not have correct ServiceName property,Routes for aggregateRoute /api/setting-management/settings/by-current-user either do not exist or do not have correct ServiceName property)
 ---> System.Exception: Unable to start Ocelot, errors are: Routes for aggregateRoute /api/setting-management/settings/by-global either do not exist or do not have correct ServiceName property,Routes for aggregateRoute /api/setting-management/settings/by-current-tenant either do not exist or do not have correct ServiceName property,Routes for aggregateRoute /api/setting-management/settings/by-current-user either do not exist or do not have correct ServiceName property
   at Ocelot.Middleware.OcelotMiddlewareExtensions.ThrowToStopOcelotStarting(Response config)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.CreateConfiguration(IApplicationBuilder builder)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at LINGYUN.MicroService.Internal.ApiGateway.InternalApiGatewayModule.OnApplicationInitialization(ApplicationInitializationContext context) in E:\Opensource\\abp-next-admin\gateways\internal\LINGYUN.MicroService.Internal.ApiGateway\src\LINGYUN.MicroService.Internal.ApiGateway\InternalApiGatewayModule.cs:line 84
   at Volo.Abp.Modularity.AbpModule.OnApplicationInitializationAsync(ApplicationInitializationContext context)
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.InitializeAsync(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   --- End of inner exception stack trace ---
   at Volo.Abp.Modularity.ModuleManager.InitializeModulesAsync(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModulesAsync()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.InitializeAsync(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplicationAsync(IApplicationBuilder app)
   at LINGYUN.MicroService.Internal.ApiGateway.Program.Main(String[] args) 
````

**Comment by sonce** [comment]
是聚合路由配置中的子路由不存在。
