### ISSUE TITLE
ElasticSearch Could not authenticate with the specified node

### ISSUE THREAD

**Issue by sonce** [colinin/abp-next-admin#669]
你好，
运行程序出现了下面的WRN提示。说无法授权用户，于是修改了Serilog的ES配置。增加了授权信息，但问题还在。
请指点下。

``` shell
2022-08-28 11:28:08 [WRN] [LINGYUN.Abp.AuditLogging.Elasticsearch.IndexInitializer] [18204] [4] - Failed to initialize index and security log may not be retrieved.
2022-08-28 11:28:08 [WRN] [LINGYUN.Abp.AuditLogging.Elasticsearch.IndexInitializer] [18204] [4] - Elasticsearch.Net.ElasticsearchClientException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration. Call: Status code 401 from: PUT /abp.dev.auditing-security-log. ServerError: Type: security_exception Reason: "unable to authenticate user [] for REST request [/abp.dev.auditing-security-log]"
 ---> Elasticsearch.Net.PipelineException: Could not authenticate with the specified node. Try verifying your credentials or check your Shield configuration.
   at Elasticsearch.Net.RequestPipeline.ThrowBadAuthPipelineExceptionWhenNeeded(IApiCallDetails details, IElasticsearchResponse response)
   at Elasticsearch.Net.RequestPipeline.PostCallElasticsearch[TResponse](RequestData requestData, TResponse response, Diagnostic`2 diagnostic, Auditable audit)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
```
``` json
"Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "DotNetCore": "Debug",
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Args": {
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level:u3}] [{SourceContext}] [{ProcessId}] [{ThreadId}] - {Message:lj}{NewLine}{Exception}",
          "restrictedToMinimumLevel": "Debug"
        },
        "Name": "Console"
      },
      {
        "Args": {
          "autoRegisterTemplate": "True",
          "autoRegisterTemplateVersion": "ESv7",
          "connectionGlobalHeaders": "Authorization=Basic elastic:password TO Base64",
          "indexFormat": "abp.dev.logging-{0:yyyy.MM.dd}",
          "nodeUris": "http://elastic:password@es:19200"
        },
        "Name": "Elasticsearch"
      }
    ]
  }
```

**Comment by sonce** [comment]
少改了一处地方。
``` json
"Elasticsearch": {
    "NodeUris": "http://elastic:password@elasticsearch:19200"
  }
```
