### ISSUE TITLE
使用 Serilog写入Critical查询失败

### ISSUE THREAD

**Issue by zhangzw218** [colinin/abp-next-admin#907]
使用Serilog写入Critical级别的日志，实际上存在数据库中的是Fatal。
这时候，再用Critical去查询日志，只能查出空值。
如果不传递日志级别直接查询数据，就会报错：
```
2023-11-17 15:09:16 [ERR] [Volo.Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter] [32172] [6] - Requested value 'Fatal' was not found.
Elasticsearch.Net.UnexpectedElasticsearchClientException: Requested value 'Fatal' was not found.
 ---> System.ArgumentException: Requested value 'Fatal' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Elasticsearch.Net.Utf8Json.Formatters.EnumFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[], JsonReader&, IJsonFormatterResolver)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.SourceFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[], JsonReader&, IJsonFormatterResolver)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[], JsonReader&, IJsonFormatterResolver)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[], JsonReader&, IJsonFormatterResolver)
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String productName, String mimeType, CancellationToken cancellationToken)
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
   at Nest.ElasticClient.SearchAsync[TDocument](ISearchRequest request, CancellationToken ct)
   at Nest.ElasticClient.SearchAsync[TDocument](Func`2 selector, CancellationToken ct)
```

**Comment by colinin** [comment]
Serilog中日志存储只有如下几个级别
https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs

**Comment by zhangzw218** [comment]
> Serilog中日志存储只有如下几个级别 https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs

嗯，我知道。
所以问题就在于，存储在es中的是Serilog的枚举，而用于查询以及返回的Dto中，日志级别用的是netcore那个日志枚举

**Comment by zhangzw218** [comment]
> Serilog中日志存储只有如下几个级别 https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs

https://github.com/colinin/abp-next-admin/blob/rel-7.2.1/aspnet-core/modules/logging/LINGYUN.Abp.Logging.Serilog.Elasticsearch/LINGYUN/Abp/AuditLogging/Serilog/Elasticsearch/SerilogElasticsearchLoggingManager.cs
问题在这里，GetListAsync方法，条件是 Microsoft.Extensions.Logging.LogLevel? level = null,，返回的LogInfo里面，也是Microsoft.Extensions.Logging.LogLevel
导致反序列化失败，提示了上面的错误：
Elasticsearch.Net.UnexpectedElasticsearchClientException: Requested value 'Fatal' was not found.

**Comment by colinin** [comment]
> > Serilog中日志存储只有如下几个级别 https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs
> 
> https://github.com/colinin/abp-next-admin/blob/rel-7.2.1/aspnet-core/modules/logging/LINGYUN.Abp.Logging.Serilog.Elasticsearch/LINGYUN/Abp/AuditLogging/Serilog/Elasticsearch/SerilogElasticsearchLoggingManager.cs 问题在这里，GetListAsync方法，条件是 Microsoft.Extensions.Logging.LogLevel? level = null,，返回的LogInfo里面，也是Microsoft.Extensions.Logging.LogLevel 导致反序列化失败，提示了上面的错误： Elasticsearch.Net.UnexpectedElasticsearchClientException: Requested value 'Fatal' was not found.

后面会重新对查询字段做映射

**Comment by zhangzw218** [comment]
> > > Serilog中日志存储只有如下几个级别 https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs
> > 
> > 
> > https://github.com/colinin/abp-next-admin/blob/rel-7.2.1/aspnet-core/modules/logging/LINGYUN.Abp.Logging.Serilog.Elasticsearch/LINGYUN/Abp/AuditLogging/Serilog/Elasticsearch/SerilogElasticsearchLoggingManager.cs 问题在这里，GetListAsync方法，条件是 Microsoft.Extensions.Logging.LogLevel? level = null,，返回的LogInfo里面，也是Microsoft.Extensions.Logging.LogLevel 导致反序列化失败，提示了上面的错误： Elasticsearch.Net.UnexpectedElasticsearchClientException: Requested value 'Fatal' was not found.
> 
> 后面会重新对查询字段做映射

好的，那么，目前针对这个es的系统日志查询，应该是无法使用的（如果日志中有Critical级别，即便查询所有日志，也会直接提示错误）
